<a href="https://colab.research.google.com/github/chernoskutov1989dv/Self-Education/blob/main/sentiment_analysis_se_24_chernoskutov_dmitry.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import re

from tensorflow.keras.layers import Dense, LSTM, Input, Dropout, Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
open ("/content/train_data_true.txt")
open ("/content/train_data_false.txt")


<_io.TextIOWrapper name='/content/train_data_false.txt' mode='r' encoding='UTF-8'>

In [ ]:
with open ("train_data_true.txt", "r", encoding = "utf-8") as f:
    texts_true = f.readlines()
    texts_true [0] = texts_true[0].replace ("\ufeff", " ")


In [ ]:
with open ("train_data_false.txt", "r", encoding = "utf-8") as f:
    texts_false = f.readlines()
    texts_false [0] = texts_false[0].replace ("\ufeff", " ")



In [ ]:

texts = texts_true + texts_false

count_true = len(texts_true)

count_false = len(texts_false)

total_lines = count_true + count_false


In [ ]:
print (count_true, count_false, total_lines)

84 88 172


In [ ]:
maxWordsCount = 1000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»', lower=True, split=' ', char_level=False)
tokenizer.fit_on_texts(texts)

dist = list(tokenizer.word_counts.items())
print(dist[:10])
print(texts[0][:100])


[('думайте', 1), ('позитивно', 4), ('и', 50), ('верьте', 3), ('в', 38), ('свою', 4), ('способность', 1), ('достигать', 1), ('отличных', 1), ('результатов', 1)]
 Думайте позитивно и верьте в свою способность достигать отличных результатов. 



In [ ]:
max_text_len = 10
data = tokenizer.texts_to_sequences(texts)
data_pad = pad_sequences(data, maxlen=max_text_len)
print(data_pad)
print( list(tokenizer.word_index.items()) )



[[197  54   2 ... 199 200 201]
 [  0   4 202 ... 205   3  67]
 [206   3  67 ...   4 208 209]
 ...
 [  0  20  62 ...  53 850 851]
 [  0   0  43 ...  33   1 853]
 [  0   0   0 ...  70  65 194]]
[('не', 1), ('и', 2), ('в', 3), ('вы', 4), ('на', 5), ('я', 6), ('а', 7), ('только', 8), ('что', 9), ('все', 10), ('это', 11), ('если', 12), ('жизнь', 13), ('просто', 14), ('с', 15), ('чем', 16), ('никогда', 17), ('чтобы', 18), ('к', 19), ('у', 20), ('больше', 21), ('себя', 22), ('то', 23), ('всегда', 24), ('вас', 25), ('меня', 26), ('за', 27), ('вам', 28), ('когда', 29), ('от', 30), ('мне', 31), ('быть', 32), ('жизни', 33), ('есть', 34), ('но', 35), ('сделать', 36), ('без', 37), ('позитивным', 38), ('никому', 39), ('как', 40), ('ты', 41), ('тем', 42), ('для', 43), ('день', 44), ('позитивное', 45), ('своих', 46), ('мы', 47), ('много', 48), ('тебя', 49), ('никто', 50), ('такой', 51), ('деньги', 52), ('денег', 53), ('позитивно', 54), ('свою', 55), ('которые', 56), ('значит', 57), ('так', 58), ('них'

In [ ]:
print (list (tokenizer.word_index.items()))
X = data_pad
Y = np.array ([[1, 0]] * count_true +[[0, 1]] *count_false)
print (X.shape, Y.shape)
indeces = np.random.choice(X.shape[0], size=X.shape[0], replace=False)
X = X[indeces]
Y = Y[indeces]



[('не', 1), ('и', 2), ('в', 3), ('вы', 4), ('на', 5), ('я', 6), ('а', 7), ('только', 8), ('что', 9), ('все', 10), ('это', 11), ('если', 12), ('жизнь', 13), ('просто', 14), ('с', 15), ('чем', 16), ('никогда', 17), ('чтобы', 18), ('к', 19), ('у', 20), ('больше', 21), ('себя', 22), ('то', 23), ('всегда', 24), ('вас', 25), ('меня', 26), ('за', 27), ('вам', 28), ('когда', 29), ('от', 30), ('мне', 31), ('быть', 32), ('жизни', 33), ('есть', 34), ('но', 35), ('сделать', 36), ('без', 37), ('позитивным', 38), ('никому', 39), ('как', 40), ('ты', 41), ('тем', 42), ('для', 43), ('день', 44), ('позитивное', 45), ('своих', 46), ('мы', 47), ('много', 48), ('тебя', 49), ('никто', 50), ('такой', 51), ('деньги', 52), ('денег', 53), ('позитивно', 54), ('свою', 55), ('которые', 56), ('значит', 57), ('так', 58), ('них', 59), ('мечты', 60), ('нужно', 61), ('того', 62), ('ничего', 63), ('лучше', 64), ('надо', 65), ('верьте', 66), ('понедельник', 67), ('живи', 68), ('позволяйте', 69), ('хорошее', 70), ('можете

In [ ]:
model = Sequential()
model.add(Embedding(maxWordsCount, 128, input_length = max_text_len))
model.add(LSTM(128, return_sequences=True))
model.add(LSTM(64))
model.add(Dense (2, activation = "softmax"))
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 10, 128)           128000    
                                                                 
 lstm_4 (LSTM)               (None, 10, 128)           131584    
                                                                 
 lstm_5 (LSTM)               (None, 64)                49408     
                                                                 
 dense_2 (Dense)             (None, 2)                 130       
                                                                 
Total params: 309,122
Trainable params: 309,122
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer = Adam (0.0001))

In [ ]:
history = model.fit(X, Y, batch_size=32, epochs=50)

Epoch 1/50
6/6 [==============================] - 3s 20ms/step - loss: 0.6915 - accuracy: 0.5814
Epoch 2/50
6/6 [==============================] - 0s 20ms/step - loss: 0.6877 - accuracy: 0.6337
Epoch 3/50
6/6 [==============================] - 0s 21ms/step - loss: 0.6837 - accuracy: 0.7616
Epoch 4/50
6/6 [==============================] - 0s 19ms/step - loss: 0.6791 - accuracy: 0.7849
Epoch 5/50
6/6 [==============================] - 0s 20ms/step - loss: 0.6736 - accuracy: 0.8140
Epoch 6/50
6/6 [==============================] - 0s 22ms/step - loss: 0.6663 - accuracy: 0.8256
Epoch 7/50
6/6 [==============================] - 0s 21ms/step - loss: 0.6561 - accuracy: 0.8430
Epoch 8/50
6/6 [==============================] - 0s 19ms/step - loss: 0.6437 - accuracy: 0.8547
Epoch 9/50
6/6 [==============================] - 0s 19ms/step - loss: 0.6258 - accuracy: 0.8547
Epoch 10/50
6/6 [==============================] - 0s 19ms/step - loss: 0.6037 - accuracy: 0.8605
Epoch 11/50
6/6 [============

In [ ]:
reverse_word_map = dict (map(reversed, tokenizer.word_index.items()))


In [ ]:
def sequence_to_text(list_of_indices):
    words = [reverse_word_map.get(letter) for letter in list_of_indices]
    return (words)


In [ ]:
t = "Не доверяй никому".lower()
#t = "Я люблю позитивное настроение".lower()

In [ ]:
data = tokenizer.texts_to_sequences([t])


In [ ]:
data_pad = pad_sequences(data, maxlen=max_text_len)
print (sequence_to_text(data[0]))
res = model.predict(data_pad) 

['не', 'доверяй', 'никому']
1/1 [==============================] - 1s 628ms/step


In [ ]:

print(res, np.argmax(res), sep='\n')

[[0.13924108 0.86075896]]
1
